name: tensorflow-metal
channels:
  - apple
  - conda-forge
dependencies:
  - nomkl
  - tensorflow==2.9.1
  - tensorflow-deps==2.9
  - pip
  - pip:
    - tensorflow-macos
    - tensorflow-metal

# CONDA_SUBDIR=osx-arm64 conda env create -f environment.yml
# conda activate tensorflow-metal
# conda env update -f environment.yml